## Problems_2

In [26]:
import torch

**Задача 1.**

[Ссылка на задачу](https://stepik.org/lesson/236466/step/5?unit=208889)

In [31]:
w = torch.tensor([[5., 10.], [1., 2.]], requires_grad=True)
function =  (w + 7).log().log().prod()
function.backward()

In [32]:
print(w.grad) # Для самопроверки

tensor([[0.0201, 0.0109],
        [0.0449, 0.0351]])


**Задача 2.**

[Ссылка на задачу](https://stepik.org/lesson/236466/step/7?unit=208889)

In [37]:
w = torch.tensor([[5., 10.], [1., 2.]], requires_grad=True)
alpha = 0.001

for i in range(500):
    function = (w + 7).log().log().prod()
    function.backward()
    w.data -= alpha * w.grad # Здесь движемся на одну итерацию вперед, причем меняем именно данные тензора
    w.grad.zero_() # Здесь сбрасываем градиент, точнее, обнуляем его
                   # (если этого не делать, то после каждой итерации он будет суммироваться)

In [38]:
print(w.data) # Для самопроверки

tensor([[4.9900, 9.9948],
        [0.9775, 1.9825]])


**Задача 3.**

[Ссылка на задачу](https://stepik.org/lesson/236466/step/9?unit=208889)

In [45]:
import torch

w = torch.tensor([[5., 10.], [1., 2.]], requires_grad=True)
optimizer = torch.optim.SGD([w], lr=0.001)

for _ in range(500):
    function = (w + 7).log().log().prod()
    function.backward()
    optimizer.step() # Оптимайзер сам делает переход на следующую итерацию, так как метод backward был выполнен, т.е посчитали градиент 
    optimizer.zero_grad()


In [46]:
print(w)

tensor([[4.9900, 9.9948],
        [0.9775, 1.9825]], requires_grad=True)
